### ISSUE TITLE
cert validity too long

### ISSUE THREAD

**Issue by waffledonkey** [sebastienheyd/docker-self-signed-proxy-companion#1]
Hello,

I hope this finds you well.  After importing ca.crt into my mac's keychain (where you end up if you click on manage certificates from within Chrome; on a mac) and giving the self-signed CA cert explicit trust for all uses (SNI, SSL, email, etc. -- something I normally do not do) Chrome continues to throw an error, this time stating that the validity is too long.  I'm sure you meant well, but was there a reason you opted for 20 years? Can I talk you out of that or making it a parameter we can pass in?  

If I don't use Docker and I just use my own self-signed certs with a 10 year expiration, import the CA cert into the keychain, trust it (only SSL) it all works perfectly, no errors, no having to force the browser to let me view the page, no "untrusted" in the URL bar even after giving it limited trust, etc.  I don't know of any registrar that will allow you to register for more than 10 years so my guess is that just because mkcert does, it's not technically valid.

**Comment by sebastienheyd** [comment]
Hello,

I had put 20 years because openssl accepted it... and to be quiet for a while :)

I added an environment variable EXPIRATION to set the certificates expiration in days. I set 3650 days as the default value (10 years).

After image update, I invite you to delete the contents of the folder containing the certificates generated by this container (probably certs), restart the container and install the new CA certificate.

I took the opportunity to optimize the image and switch to the latest version of Alpine ;)

Please tell me if it works on Mac, thanks !

**Comment by waffledonkey** [comment]
That worked a treat; thank you, but it seems I have mislead you.

Unsure if you would address my issue, I had written BASH scripts to create certs manually -- ahead of up'ing, but while trying 10 years, 5 years, 3 years, etc. I was repeatedly running into the same exact error about cert validity being too long.  It seems that in 2020, [Safari](https://www.ssl.com/blogs/apple-limits-ssl-tls-certificate-lifetimes-to-398-days) and [Chrome](https://chromium.googlesource.com/chromium/src/+/HEAD/net/docs/certificate_lifetimes.md) (others?) settled on 398 days, advising **397 days to be safe**.

The reason my previously generated self-signed cert worked is because I created it 7 years ago and it was grandfathered in...

**Comment by sebastienheyd** [comment]
Just to make sure I got it right, you defined 397 days to make it work?

Because according to the Google article: 

* Does this apply to locally-operated CAs, such as those used within enterprises that use enterprise-configured configured CAs?
  * No. This only applies to the set of CAs that are trusted by default by Google Chrome, and not CAs that are operated by an enterprise and that have no certification paths to CAs that are trusted by default.

**Comment by waffledonkey** [comment]
in my self-authored bash scripts, 3 years did not work.  365 days did, so I was using that...  With your thing, I opted for 397 and it also worked.  To satisfy the question; I moved my existing certs dir out of the way, commented out the EXPIRATION env in docker-compose.yml, re-up'd and added the newly generated 10 year (default) ca.crt to the keychain and I get the cert validity too long error (in Chrome).  

I'm going back to 397.
